# Strategy Configuration

# Simple Momentum Strategy (Step 1 & 2)
momentum_strategy:
  name: "Simple Momentum Long/Short"

  # Coin Selection
  selection:
    top_n_by_volume: 21  # Select top N coins by volume
    volume_metric: tp_volume  # typical_price * volume

  # Indicator Parameters
  indicators:
    momentum_period: 20  # Can be 7, 14, 20, 21, 60

  # Position Sizing
  positions:
    long_top_n: 5
    short_bottom_n: 5
    equal_weight: true

  # Filters (optional)
  filters:
    apply_noise_filter: false
    noise_threshold: 0.7
    noise_period: 15

# Market Timing Strategy (Step 3)
market_timing_strategy:
  name: "Dual Momentum with Market Timing"

  # Coin Selection
  selection:
    top_n_by_volume: 21
    volume_metric: tp_volume

  # Market Regime Detection
  regime:
    reference_coins: [BTC/USDT, ETH/USDT]
    ema_period: 50
    # If any reference coin below EMA50 → bear market → short mode

  # Position Sizing
  positions:
    bull_market:
      long_top_n: 4
      use_short: false
    bear_market:
      long_top_n: 0
      short_bottom_n: 8

  # Leverage Rules
  leverage:
    # Long side (bull market)
    long_base:
      - condition: "mom7 > 0"
        leverage: 1
      - condition: "mom20 > 0"
        leverage: 1
    long_timing:
      - condition: "close > close_prev"
        leverage: -1

    # Short side (bear market)
    short_base:
      - condition: "close < ema7"
        leverage: -1
      - condition: "close < ema20"
        leverage: -1
    short_timing:
      - condition: "close < close_prev"
        leverage: 1

    max_leverage: 3

  # Indicators
  indicators:
    momentum_periods: [7, 20]
    ema_periods: [7, 20, 30, 40, 50]
    noise_period: 15

  # Filters
  filters:
    apply_noise_filter: true
    noise_threshold: 0.7

# Parameter Optimization Settings
optimization:
  momentum_periods_to_test: [5, 7, 10, 14, 20, 21, 30, 60]
  noise_thresholds_to_test: [0.6, 0.65, 0.7, 0.75, 0.8]
  top_n_values_to_test: [3, 4, 5, 6, 7]

  # Walk-forward validation
  walk_forward:
    train_window_days: 90
    test_window_days: 30
    step_days: 30
