name: systemtrading
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - scikit-learn
  - ipykernel
  - pyyaml
  - pip
  - pip:
    - python-binance
    - mplfinance
